### ISSUE TITLE
open_database fails

### ISSUE THREAD

**Issue by SimonWoods** [TacHawkes/HITRAN.jl#15] opened 2022-05-19 21:09 UTC
I can't open a database any more:

```
julia> using HITRAN

julia> HITRAN.open_database("test.sqlite")
ERROR: MethodError: no method matching haskey(::Vector{SQLite.DBTable}, ::Symbol)
```

**Comment by TacHawkes** [comment] 2022-05-20 05:15
Thanks for reporting. I can confirm that. I have to take a look what changed in the SQLite API and will try to fix it asap.

**Comment by TacHawkes** [comment] 2022-05-20 05:22
Short follow-up. This broke down due to https://github.com/JuliaDatabases/SQLite.jl/pull/269 
So that release was in fact breaking instead of a patch release...

I will create an easy fix for this but I have not reviewed the changes in SQLite for some time and their API has much improved so I could actually simplify some of my internal code where I have tried hard to have type-stable access to the database fields.

**Closed as completed** 2022-05-20 15:36 UTC
